### ISSUE TITLE
0516/아두이노 issue

### ISSUE THREAD

**Issue by mkshin96** [yks095/Project-SmartPot#1]
계절마다 물 주는 주기를 달리하기 위해 현재 몇월인가가 필수적인데, db에 request를 날릴 것인가, 아두이노에서 library를 사용할 것인가?

**Comment by yks095** [comment]
> 계절마다 물 주는 주기를 달리하기 위해 현재 몇월인가가 필수적인데, db에 request를 날릴 것인가, 아두이노에서 library를 사용할 것인가?

라이브러리를 사용하는게 좋을 것 같습니다.

**Comment by mkshin96** [comment]
아두이노 library를 사용하니, 메모리를 많이 잡아먹는 문제가 있어, db에 request를 날리는 방식으로 구현 완료
